// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

/*
Package config is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	Config
	Node
	Location
	EnergyCost
	TimeDelay
*/
package config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type E_Protocol int32

const (
	E_Protocol_UNSET   E_Protocol = 0
	E_Protocol_DIRECT  E_Protocol = 1
	E_Protocol_LEACH   E_Protocol = 2
	E_Protocol_APTEEN  E_Protocol = 3
	E_Protocol_PEGASIS E_Protocol = 4
)

var E_Protocol_name = map[int32]string{
	0: "UNSET",
	1: "DIRECT",
	2: "LEACH",
	3: "APTEEN",
	4: "PEGASIS",
}
var E_Protocol_value = map[string]int32{
	"UNSET":   0,
	"DIRECT":  1,
	"LEACH":   2,
	"APTEEN":  3,
	"PEGASIS": 4,
}

func (x E_Protocol) String() string {
	return proto.EnumName(E_Protocol_name, int32(x))
}
func (E_Protocol) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Config struct {
	// Simulation protocol.
	Protocol E_Protocol `protobuf:"varint,1,opt,name=protocol,enum=config.E_Protocol" json:"protocol,omitempty"`
	// Number of maximum rounds in simulation.
	MaxRounds int64 `protobuf:"varint,2,opt,name=max_rounds,json=maxRounds" json:"max_rounds,omitempty"`
	// Percentage of cluster heads among all nodes [0, 1].
	PClusterHeads float64 `protobuf:"fixed64,3,opt,name=p_cluster_heads,json=pClusterHeads" json:"p_cluster_heads,omitempty"`
	// Size of data sent by individual node (in Bytes).
	MsgLength int64 `protobuf:"varint,4,opt,name=msg_length,json=msgLength" json:"msg_length,omitempty"`
	// Nodes points to configuration for each node.
	Nodes []*Node `protobuf:"bytes,5,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Config) GetProtocol() E_Protocol {
	if m != nil {
		return m.Protocol
	}
	return E_Protocol_UNSET
}

func (m *Config) GetMaxRounds() int64 {
	if m != nil {
		return m.MaxRounds
	}
	return 0
}

func (m *Config) GetPClusterHeads() float64 {
	if m != nil {
		return m.PClusterHeads
	}
	return 0
}

func (m *Config) GetMsgLength() int64 {
	if m != nil {
		return m.MsgLength
	}
	return 0
}

func (m *Config) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// Node defines a configuration for a single node.
type Node struct {
	// Unique ID for a node.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Initial value of energy (in Joules).
	InitialEnergy float64 `protobuf:"fixed64,2,opt,name=initial_energy,json=initialEnergy" json:"initial_energy,omitempty"`
	// Location of a node in 2D space.
	Location *Location `protobuf:"bytes,4,opt,name=location" json:"location,omitempty"`
	// Energy consumption of node operations.
	EnergyCost *EnergyCost `protobuf:"bytes,5,opt,name=energy_cost,json=energyCost" json:"energy_cost,omitempty"`
	// Time delays introduced by node operations
	TimeDelay *TimeDelay `protobuf:"bytes,6,opt,name=time_delay,json=timeDelay" json:"time_delay,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Node) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Node) GetInitialEnergy() float64 {
	if m != nil {
		return m.InitialEnergy
	}
	return 0
}

func (m *Node) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Node) GetEnergyCost() *EnergyCost {
	if m != nil {
		return m.EnergyCost
	}
	return nil
}

func (m *Node) GetTimeDelay() *TimeDelay {
	if m != nil {
		return m.TimeDelay
	}
	return nil
}

// Location defines a X, Y coordinates of a node.
type Location struct {
	X float64 `protobuf:"fixed64,1,opt,name=X,json=x" json:"X,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=Y,json=y" json:"Y,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Location) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Location) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

// EnergyCost defines energy consumption for common node operations.
type EnergyCost struct {
	// Energy required to transmit one byte (in nanojoules).
	Transmit int64 `protobuf:"varint,1,opt,name=transmit" json:"transmit,omitempty"`
	// Energy required to receive one byte (in nanojoules).
	Receive int64 `protobuf:"varint,2,opt,name=receive" json:"receive,omitempty"`
	// Energy required to listen the channel for a second (in nanojoules).
	Listen int64 `protobuf:"varint,3,opt,name=listen" json:"listen,omitempty"`
	// Energy required to process sensor data (in nanojoules).
	SensorDataProcess int64 `protobuf:"varint,4,opt,name=sensor_data_process,json=sensorDataProcess" json:"sensor_data_process,omitempty"`
	// Energy required to wake up MCU (in nanojoules).
	WakeUpMcu int64 `protobuf:"varint,5,opt,name=wake_up_mcu,json=wakeUpMcu" json:"wake_up_mcu,omitempty"`
}

func (m *EnergyCost) Reset()                    { *m = EnergyCost{} }
func (m *EnergyCost) String() string            { return proto.CompactTextString(m) }
func (*EnergyCost) ProtoMessage()               {}
func (*EnergyCost) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EnergyCost) GetTransmit() int64 {
	if m != nil {
		return m.Transmit
	}
	return 0
}

func (m *EnergyCost) GetReceive() int64 {
	if m != nil {
		return m.Receive
	}
	return 0
}

func (m *EnergyCost) GetListen() int64 {
	if m != nil {
		return m.Listen
	}
	return 0
}

func (m *EnergyCost) GetSensorDataProcess() int64 {
	if m != nil {
		return m.SensorDataProcess
	}
	return 0
}

func (m *EnergyCost) GetWakeUpMcu() int64 {
	if m != nil {
		return m.WakeUpMcu
	}
	return 0
}

// TimeDelay defines time delays for common node operations.
type TimeDelay struct {
	// Time required to process sensor data (in nanoseconds).
	SensorDataProcess int64 `protobuf:"varint,1,opt,name=sensor_data_process,json=sensorDataProcess" json:"sensor_data_process,omitempty"`
	// Time required to wake up MCU (in nanoseconds).
	WakeUpMcu int64 `protobuf:"varint,2,opt,name=wake_up_mcu,json=wakeUpMcu" json:"wake_up_mcu,omitempty"`
}

func (m *TimeDelay) Reset()                    { *m = TimeDelay{} }
func (m *TimeDelay) String() string            { return proto.CompactTextString(m) }
func (*TimeDelay) ProtoMessage()               {}
func (*TimeDelay) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TimeDelay) GetSensorDataProcess() int64 {
	if m != nil {
		return m.SensorDataProcess
	}
	return 0
}

func (m *TimeDelay) GetWakeUpMcu() int64 {
	if m != nil {
		return m.WakeUpMcu
	}
	return 0
}

func init() {
	proto.RegisterType((*Config)(nil), "config.Config")
	proto.RegisterType((*Node)(nil), "config.Node")
	proto.RegisterType((*Location)(nil), "config.Location")
	proto.RegisterType((*EnergyCost)(nil), "config.EnergyCost")
	proto.RegisterType((*TimeDelay)(nil), "config.TimeDelay")
	proto.RegisterEnum("config.E_Protocol", E_Protocol_name, E_Protocol_value)
}

func init() { proto.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xed, 0x8a, 0xd3, 0x40,
	0x14, 0x75, 0x9a, 0x36, 0xdb, 0xde, 0x76, 0x6b, 0xf6, 0x0a, 0x12, 0x04, 0xa5, 0x04, 0x5c, 0x8a,
	0x48, 0x91, 0xee, 0x13, 0x94, 0x36, 0xec, 0x2e, 0xd4, 0x52, 0xa6, 0x5d, 0x50, 0xfc, 0x31, 0x8c,
	0xc9, 0xd8, 0x1d, 0x4c, 0x32, 0x21, 0x33, 0xd5, 0xf6, 0x95, 0x7c, 0x0c, 0x1f, 0xc1, 0x27, 0x92,
	0x4c, 0x92, 0x16, 0x04, 0x61, 0xff, 0xdd, 0x73, 0xce, 0xdc, 0x73, 0xbf, 0x06, 0x06, 0x91, 0xca,
	0xbe, 0xc9, 0xdd, 0x24, 0x2f, 0x94, 0x51, 0xe8, 0x56, 0x28, 0xf8, 0x4d, 0xc0, 0x9d, 0xdb, 0x10,
	0x27, 0xd0, 0xb5, 0x5a, 0xa4, 0x12, 0x9f, 0x8c, 0xc8, 0x78, 0x38, 0xc5, 0x49, 0x9d, 0x13, 0xb2,
	0x75, 0xad, 0xd0, 0xd3, 0x1b, 0x7c, 0x0d, 0x90, 0xf2, 0x03, 0x2b, 0xd4, 0x3e, 0x8b, 0xb5, 0xdf,
	0x1a, 0x91, 0xb1, 0x43, 0x7b, 0x29, 0x3f, 0x50, 0x4b, 0xe0, 0x35, 0x3c, 0xcf, 0x59, 0x94, 0xec,
	0xb5, 0x11, 0x05, 0x7b, 0x14, 0x3c, 0xd6, 0xbe, 0x33, 0x22, 0x63, 0x42, 0x2f, 0xf3, 0x79, 0xc5,
	0xde, 0x95, 0xa4, 0xb5, 0xd1, 0x3b, 0x96, 0x88, 0x6c, 0x67, 0x1e, 0xfd, 0x76, 0x6d, 0xa3, 0x77,
	0x4b, 0x4b, 0x60, 0x00, 0x9d, 0x4c, 0xc5, 0x42, 0xfb, 0x9d, 0x91, 0x33, 0xee, 0x4f, 0x07, 0x4d,
	0x4b, 0x2b, 0x15, 0x0b, 0x5a, 0x49, 0xc1, 0x1f, 0x02, 0xed, 0x12, 0xe3, 0x10, 0x5a, 0x32, 0xb6,
	0xcd, 0x3b, 0xb4, 0x25, 0x63, 0x7c, 0x0b, 0x43, 0x99, 0x49, 0x23, 0x79, 0xc2, 0x44, 0x26, 0x8a,
	0xdd, 0xd1, 0xb6, 0x49, 0xe8, 0x65, 0xcd, 0x86, 0x96, 0xc4, 0xf7, 0xd0, 0x4d, 0x54, 0xc4, 0x8d,
	0x54, 0x99, 0x6d, 0xa0, 0x3f, 0xf5, 0x9a, 0x32, 0xcb, 0x9a, 0xa7, 0xa7, 0x17, 0x78, 0x03, 0xfd,
	0xca, 0x8c, 0x45, 0x4a, 0x1b, 0xbf, 0x63, 0x13, 0xce, 0xab, 0xb2, 0xd2, 0x5c, 0x69, 0x43, 0x41,
	0x9c, 0x62, 0xfc, 0x00, 0x60, 0x64, 0x2a, 0x58, 0x2c, 0x12, 0x7e, 0xf4, 0x5d, 0x9b, 0x73, 0xd5,
	0xe4, 0x6c, 0x65, 0x2a, 0x16, 0xa5, 0x40, 0x7b, 0xa6, 0x09, 0x83, 0x6b, 0xe8, 0x36, 0xc5, 0x71,
	0x00, 0xe4, 0x93, 0x1d, 0x8b, 0x50, 0x72, 0x28, 0xd1, 0xe7, 0x7a, 0x10, 0x72, 0x0c, 0x7e, 0x11,
	0x80, 0x73, 0x51, 0x7c, 0x05, 0x5d, 0x53, 0xf0, 0x4c, 0xa7, 0xd2, 0xd4, 0x8b, 0x38, 0x61, 0xf4,
	0xe1, 0xa2, 0x10, 0x91, 0x90, 0x3f, 0x44, 0x7d, 0xae, 0x06, 0xe2, 0x4b, 0x70, 0x13, 0xa9, 0x8d,
	0xc8, 0xec, 0x8d, 0x1c, 0x5a, 0x23, 0x9c, 0xc0, 0x0b, 0x2d, 0x32, 0xad, 0x0a, 0x16, 0x73, 0xc3,
	0x59, 0x5e, 0xa8, 0x48, 0x68, 0x5d, 0x5f, 0xe9, 0xaa, 0x92, 0x16, 0xdc, 0xf0, 0x75, 0x25, 0xe0,
	0x1b, 0xe8, 0xff, 0xe4, 0xdf, 0x05, 0xdb, 0xe7, 0x2c, 0x8d, 0xf6, 0x76, 0x37, 0x0e, 0xed, 0x95,
	0xd4, 0x43, 0xfe, 0x31, 0xda, 0x07, 0x5f, 0xa0, 0x77, 0x1a, 0xf6, 0x7f, 0xe6, 0xe4, 0x89, 0xe6,
	0xad, 0x7f, 0xcc, 0xdf, 0xdd, 0x02, 0x9c, 0x3f, 0x2a, 0xf6, 0xa0, 0xf3, 0xb0, 0xda, 0x84, 0x5b,
	0xef, 0x19, 0x02, 0xb8, 0x8b, 0x7b, 0x1a, 0xce, 0xb7, 0x1e, 0x29, 0xe9, 0x65, 0x38, 0x9b, 0xdf,
	0x79, 0xad, 0x92, 0x9e, 0xad, 0xb7, 0x61, 0xb8, 0xf2, 0x1c, 0xec, 0xc3, 0xc5, 0x3a, 0xbc, 0x9d,
	0x6d, 0xee, 0x37, 0x5e, 0xfb, 0xab, 0x6b, 0xff, 0xf8, 0xcd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x46, 0x0b, 0xf5, 0xf0, 0x33, 0x03, 0x00, 0x00,
}
