// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type E_Protocol int32

const (
	E_Protocol_UNSET   E_Protocol = 0
	E_Protocol_DIRECT  E_Protocol = 1
	E_Protocol_LEACH   E_Protocol = 2
	E_Protocol_APTEEN  E_Protocol = 3
	E_Protocol_PEGASIS E_Protocol = 4
)

var E_Protocol_name = map[int32]string{
	0: "UNSET",
	1: "DIRECT",
	2: "LEACH",
	3: "APTEEN",
	4: "PEGASIS",
}
var E_Protocol_value = map[string]int32{
	"UNSET":   0,
	"DIRECT":  1,
	"LEACH":   2,
	"APTEEN":  3,
	"PEGASIS": 4,
}

func (x E_Protocol) String() string {
	return proto.EnumName(E_Protocol_name, int32(x))
}
func (E_Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_config_3215483f8f8a1749, []int{0}
}

type Config struct {
	// Simulation protocol.
	Protocol E_Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=config.E_Protocol" json:"protocol,omitempty"`
	// Number of maximum rounds in simulation.
	MaxRounds int64 `protobuf:"varint,2,opt,name=max_rounds,json=maxRounds,proto3" json:"max_rounds,omitempty"`
	// Percentage of cluster heads among all nodes [0, 1].
	PClusterHeads float64 `protobuf:"fixed64,3,opt,name=p_cluster_heads,json=pClusterHeads,proto3" json:"p_cluster_heads,omitempty"`
	// Size of data sent by individual node (in Bytes).
	MsgLength int64 `protobuf:"varint,4,opt,name=msg_length,json=msgLength,proto3" json:"msg_length,omitempty"`
	// Nodes points to configuration for each node.
	Nodes                []*Node  `protobuf:"bytes,5,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_3215483f8f8a1749, []int{0}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetProtocol() E_Protocol {
	if m != nil {
		return m.Protocol
	}
	return E_Protocol_UNSET
}

func (m *Config) GetMaxRounds() int64 {
	if m != nil {
		return m.MaxRounds
	}
	return 0
}

func (m *Config) GetPClusterHeads() float64 {
	if m != nil {
		return m.PClusterHeads
	}
	return 0
}

func (m *Config) GetMsgLength() int64 {
	if m != nil {
		return m.MsgLength
	}
	return 0
}

func (m *Config) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// Node defines a configuration for a single node.
type Node struct {
	// Unique ID for a node.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Initial value of energy (in Joules).
	InitialEnergy float64 `protobuf:"fixed64,2,opt,name=initial_energy,json=initialEnergy,proto3" json:"initial_energy,omitempty"`
	// Location of a node in 2D space.
	Location *Location `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	// Energy consumption of node operations.
	EnergyCost *EnergyCost `protobuf:"bytes,5,opt,name=energy_cost,json=energyCost,proto3" json:"energy_cost,omitempty"`
	// Time delays introduced by node operations
	TimeDelay            *TimeDelay `protobuf:"bytes,6,opt,name=time_delay,json=timeDelay,proto3" json:"time_delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_3215483f8f8a1749, []int{1}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Node) GetInitialEnergy() float64 {
	if m != nil {
		return m.InitialEnergy
	}
	return 0
}

func (m *Node) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Node) GetEnergyCost() *EnergyCost {
	if m != nil {
		return m.EnergyCost
	}
	return nil
}

func (m *Node) GetTimeDelay() *TimeDelay {
	if m != nil {
		return m.TimeDelay
	}
	return nil
}

// Location defines a X, Y coordinates of a node.
type Location struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_3215483f8f8a1749, []int{2}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Location) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

// EnergyCost defines energy consumption for common node operations.
type EnergyCost struct {
	// Energy required to transmit one byte (in nanojoules).
	Transmit int64 `protobuf:"varint,1,opt,name=transmit,proto3" json:"transmit,omitempty"`
	// Energy required to receive one byte (in nanojoules).
	Receive int64 `protobuf:"varint,2,opt,name=receive,proto3" json:"receive,omitempty"`
	// Energy required to listen the channel for a second (in nanojoules).
	Listen int64 `protobuf:"varint,3,opt,name=listen,proto3" json:"listen,omitempty"`
	// Energy required to process sensor data (in nanojoules).
	SensorDataProcess int64 `protobuf:"varint,4,opt,name=sensor_data_process,json=sensorDataProcess,proto3" json:"sensor_data_process,omitempty"`
	// Energy required to wake up MCU (in nanojoules).
	WakeUpMcu            int64    `protobuf:"varint,5,opt,name=wake_up_mcu,json=wakeUpMcu,proto3" json:"wake_up_mcu,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnergyCost) Reset()         { *m = EnergyCost{} }
func (m *EnergyCost) String() string { return proto.CompactTextString(m) }
func (*EnergyCost) ProtoMessage()    {}
func (*EnergyCost) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_3215483f8f8a1749, []int{3}
}
func (m *EnergyCost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnergyCost.Unmarshal(m, b)
}
func (m *EnergyCost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnergyCost.Marshal(b, m, deterministic)
}
func (dst *EnergyCost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnergyCost.Merge(dst, src)
}
func (m *EnergyCost) XXX_Size() int {
	return xxx_messageInfo_EnergyCost.Size(m)
}
func (m *EnergyCost) XXX_DiscardUnknown() {
	xxx_messageInfo_EnergyCost.DiscardUnknown(m)
}

var xxx_messageInfo_EnergyCost proto.InternalMessageInfo

func (m *EnergyCost) GetTransmit() int64 {
	if m != nil {
		return m.Transmit
	}
	return 0
}

func (m *EnergyCost) GetReceive() int64 {
	if m != nil {
		return m.Receive
	}
	return 0
}

func (m *EnergyCost) GetListen() int64 {
	if m != nil {
		return m.Listen
	}
	return 0
}

func (m *EnergyCost) GetSensorDataProcess() int64 {
	if m != nil {
		return m.SensorDataProcess
	}
	return 0
}

func (m *EnergyCost) GetWakeUpMcu() int64 {
	if m != nil {
		return m.WakeUpMcu
	}
	return 0
}

// TimeDelay defines time delays for common node operations.
type TimeDelay struct {
	// Time required to process sensor data (in nanoseconds).
	SensorDataProcess int64 `protobuf:"varint,1,opt,name=sensor_data_process,json=sensorDataProcess,proto3" json:"sensor_data_process,omitempty"`
	// Time required to wake up MCU (in nanoseconds).
	WakeUpMcu            int64    `protobuf:"varint,2,opt,name=wake_up_mcu,json=wakeUpMcu,proto3" json:"wake_up_mcu,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeDelay) Reset()         { *m = TimeDelay{} }
func (m *TimeDelay) String() string { return proto.CompactTextString(m) }
func (*TimeDelay) ProtoMessage()    {}
func (*TimeDelay) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_3215483f8f8a1749, []int{4}
}
func (m *TimeDelay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeDelay.Unmarshal(m, b)
}
func (m *TimeDelay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeDelay.Marshal(b, m, deterministic)
}
func (dst *TimeDelay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeDelay.Merge(dst, src)
}
func (m *TimeDelay) XXX_Size() int {
	return xxx_messageInfo_TimeDelay.Size(m)
}
func (m *TimeDelay) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeDelay.DiscardUnknown(m)
}

var xxx_messageInfo_TimeDelay proto.InternalMessageInfo

func (m *TimeDelay) GetSensorDataProcess() int64 {
	if m != nil {
		return m.SensorDataProcess
	}
	return 0
}

func (m *TimeDelay) GetWakeUpMcu() int64 {
	if m != nil {
		return m.WakeUpMcu
	}
	return 0
}

func init() {
	proto.RegisterType((*Config)(nil), "config.Config")
	proto.RegisterType((*Node)(nil), "config.Node")
	proto.RegisterType((*Location)(nil), "config.Location")
	proto.RegisterType((*EnergyCost)(nil), "config.EnergyCost")
	proto.RegisterType((*TimeDelay)(nil), "config.TimeDelay")
	proto.RegisterEnum("config.E_Protocol", E_Protocol_name, E_Protocol_value)
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_config_3215483f8f8a1749) }

var fileDescriptor_config_3215483f8f8a1749 = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xef, 0x6a, 0xdb, 0x3e,
	0x14, 0xfd, 0x29, 0x4e, 0xdc, 0xe4, 0x26, 0xcd, 0xcf, 0xbd, 0x83, 0x61, 0x06, 0x1b, 0xc1, 0xb0,
	0x12, 0xc6, 0x08, 0x23, 0x7d, 0x82, 0x90, 0x98, 0xb6, 0x90, 0x85, 0xa0, 0xa4, 0xd0, 0xb2, 0x0f,
	0x42, 0xb3, 0xb5, 0x54, 0xcc, 0xb6, 0x8c, 0xa5, 0x6c, 0xed, 0x2b, 0xed, 0x31, 0xf6, 0x08, 0x7b,
	0xa2, 0x61, 0xf9, 0x4f, 0x60, 0x30, 0xd8, 0xb7, 0x7b, 0xce, 0xd1, 0x3d, 0xf7, 0x9f, 0x60, 0x14,
	0xa9, 0xec, 0x8b, 0x3c, 0xcc, 0xf2, 0x42, 0x19, 0x85, 0x6e, 0x85, 0x82, 0x9f, 0x04, 0xdc, 0xa5,
	0x0d, 0x71, 0x06, 0x7d, 0xab, 0x45, 0x2a, 0xf1, 0xc9, 0x84, 0x4c, 0xc7, 0x73, 0x9c, 0xd5, 0x39,
	0x21, 0xdb, 0xd6, 0x0a, 0x6d, 0xdf, 0xe0, 0x6b, 0x80, 0x94, 0x3f, 0xb1, 0x42, 0x1d, 0xb3, 0x58,
	0xfb, 0x9d, 0x09, 0x99, 0x3a, 0x74, 0x90, 0xf2, 0x27, 0x6a, 0x09, 0xbc, 0x84, 0xff, 0x73, 0x16,
	0x25, 0x47, 0x6d, 0x44, 0xc1, 0x1e, 0x05, 0x8f, 0xb5, 0xef, 0x4c, 0xc8, 0x94, 0xd0, 0xf3, 0x7c,
	0x59, 0xb1, 0x37, 0x25, 0x69, 0x6d, 0xf4, 0x81, 0x25, 0x22, 0x3b, 0x98, 0x47, 0xbf, 0x5b, 0xdb,
	0xe8, 0xc3, 0xda, 0x12, 0x18, 0x40, 0x2f, 0x53, 0xb1, 0xd0, 0x7e, 0x6f, 0xe2, 0x4c, 0x87, 0xf3,
	0x51, 0xd3, 0xd2, 0x46, 0xc5, 0x82, 0x56, 0x52, 0xf0, 0x8b, 0x40, 0xb7, 0xc4, 0x38, 0x86, 0x8e,
	0x8c, 0x6d, 0xf3, 0x0e, 0xed, 0xc8, 0x18, 0xdf, 0xc2, 0x58, 0x66, 0xd2, 0x48, 0x9e, 0x30, 0x91,
	0x89, 0xe2, 0xf0, 0x6c, 0xdb, 0x24, 0xf4, 0xbc, 0x66, 0x43, 0x4b, 0xe2, 0x7b, 0xe8, 0x27, 0x2a,
	0xe2, 0x46, 0xaa, 0xcc, 0x36, 0x30, 0x9c, 0x7b, 0x4d, 0x99, 0x75, 0xcd, 0xd3, 0xf6, 0x05, 0x5e,
	0xc1, 0xb0, 0x32, 0x63, 0x91, 0xd2, 0xc6, 0xef, 0xd9, 0x84, 0xd3, 0xaa, 0xac, 0xb4, 0x54, 0xda,
	0x50, 0x10, 0x6d, 0x8c, 0x1f, 0x00, 0x8c, 0x4c, 0x05, 0x8b, 0x45, 0xc2, 0x9f, 0x7d, 0xd7, 0xe6,
	0x5c, 0x34, 0x39, 0x7b, 0x99, 0x8a, 0x55, 0x29, 0xd0, 0x81, 0x69, 0xc2, 0xe0, 0x12, 0xfa, 0x4d,
	0x71, 0x1c, 0x01, 0xb9, 0xb7, 0x63, 0x11, 0x4a, 0xee, 0x4b, 0xf4, 0x50, 0x0f, 0x42, 0x1e, 0x82,
	0x1f, 0x04, 0xe0, 0x54, 0x14, 0x5f, 0x41, 0xdf, 0x14, 0x3c, 0xd3, 0xa9, 0x34, 0xf5, 0x22, 0x5a,
	0x8c, 0x3e, 0x9c, 0x15, 0x22, 0x12, 0xf2, 0x9b, 0xa8, 0xcf, 0xd5, 0x40, 0x7c, 0x09, 0x6e, 0x22,
	0xb5, 0x11, 0x99, 0xbd, 0x91, 0x43, 0x6b, 0x84, 0x33, 0x78, 0xa1, 0x45, 0xa6, 0x55, 0xc1, 0x62,
	0x6e, 0x38, 0xcb, 0x0b, 0x15, 0x09, 0xad, 0xeb, 0x2b, 0x5d, 0x54, 0xd2, 0x8a, 0x1b, 0xbe, 0xad,
	0x04, 0x7c, 0x03, 0xc3, 0xef, 0xfc, 0xab, 0x60, 0xc7, 0x9c, 0xa5, 0xd1, 0xd1, 0xee, 0xc6, 0xa1,
	0x83, 0x92, 0xba, 0xcb, 0x3f, 0x46, 0xc7, 0xe0, 0x13, 0x0c, 0xda, 0x61, 0xff, 0x66, 0x4e, 0xfe,
	0xd1, 0xbc, 0xf3, 0x87, 0xf9, 0xbb, 0x6b, 0x80, 0xd3, 0x47, 0xc5, 0x01, 0xf4, 0xee, 0x36, 0xbb,
	0x70, 0xef, 0xfd, 0x87, 0x00, 0xee, 0xea, 0x96, 0x86, 0xcb, 0xbd, 0x47, 0x4a, 0x7a, 0x1d, 0x2e,
	0x96, 0x37, 0x5e, 0xa7, 0xa4, 0x17, 0xdb, 0x7d, 0x18, 0x6e, 0x3c, 0x07, 0x87, 0x70, 0xb6, 0x0d,
	0xaf, 0x17, 0xbb, 0xdb, 0x9d, 0xd7, 0xfd, 0xec, 0xda, 0x3f, 0x7e, 0xf5, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0xa9, 0xba, 0x8b, 0x11, 0x33, 0x03, 0x00, 0x00,
}
